### ISSUE TITLE
Super slow enqueue

### ISSUE THREAD

**Issue by zshannon** [mikesmullin/CakePHP-PHP-Resque-Plugin#1]
Enqueues are consistently taking between 60 and 70 seconds via the component. From CLI, they're instantaneous. Enqueues initiated from a controller in the browser cause timeouts, and don't return a job token. Any ideas what could be causing this? I'm running PHP 5.3.5, CakePHP 1.3.1, and Redis 2.2.9 on a remote machine.

**Comment by mikesmullin** [comment]
wohoo! someone is using my crap.

you might try the legacy version of redis v2.0.5. but if the cli works i doubt that is it. other than that it is identical to my own setup, and have yet to encounter that issue.

best way to troubleshoot this sort of issues in general though is with php xdebug outputting to cachegrind and then view those files in kcachegrind. it will tell you which functions are taking the longest per-request.

uncomment line 34 of https://gist.github.com/623340 then restart apache, refresh the browser, and watch the /tmp dir

when you find out what function is getting hung up, if its related to my plugin, please do let me know! happy to look into it for you. also accepting pull requests.

hope this helps! :)

**Comment by zshannon** [comment]
Yeah man, it's a great plugin that's going to see some heavy usage, thanks for releasing it. Not sure what happened, but the issue went away inexplicably before I could even try debugging it
