### ISSUE TITLE
Losing function

### ISSUE THREAD

**Issue by doremon** [mikesmullin/CakePHP-PHP-Resque-Plugin#5]
Hi Mikes,
i setup my project like your descriptions, but when i start the resque, it shows errors : PHP Fatal error:  Call to undefined function orEquals() in app/plugins/php-resque/vendors/shells/resque.php on line 111
- i tried to find this function. but i can't . Could you help me where is it ? Thanks

**Comment by mikesmullin** [comment]
ya its very simple. something like:

`function orEquals($a, $b) { return $a? $a : $b; }`
